export type Company = {
  clientId: string;
  companyName: string;
  email: string;
  companyAlias: string;
  county: string;
  state: string;
  city: string;
  zip: string;
  phone: string;
  streetName: string;
  companyStreetNumber: string;
  buildingNumber: string;
  langId: string;
  taxId: string;
  logoUrl: string;
  name: string;
  scheduleActive: boolean;
  lastUpdated?: number;
  createdAt?: number;
  id?: number;
};
